language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  # - pip install tweepy
  # - pip install geopandas
  # - pip install rtree
  # - pip install pandas
  - pip install -e .
  - pip install pytest-cov codecov
script:
  - pytest tests --cov=src tests
after_success:
  - codecov