language: python
python:
  - "3.8"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install tweepy
  - pip install geopandas
  - pip install pandas
  - pip install -e .[test]
script:
  - pytest tests
after_success:
  - codecov